### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by anush2209** [adlerzei/letterboxd-streaming-providers#9]
![Annotation 2020-04-25 030522](https://user-images.githubusercontent.com/11133437/80258769-a5ef4700-86a1-11ea-8a9e-ccba3022d2ee.png)

It is clear from the above picture that after asking to filter Amazon Prime Video (USA), nothing happened (clearly Netflix and Disney+ exclusive content still visible).

**Comment by adlerzei** [comment]
Hello, 
Sorry for the late reply. I just updated the extension, a few requests were broken. It should now work as expected once the new update has been verified by Google/Mozilla. If you have questions, feel free to ask.
Cheerz,
Christian

**Comment by anush2209** [comment]
Hey,
The update fixed the issue. How can I contribute to adding India as a country?
